-- MySQL Script generated by MySQL Workbench
-- Thu Dec  6 21:40:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `topicos` DEFAULT CHARACTER SET utf8mb4 ;
USE `topicos` ;

-- -----------------------------------------------------
-- Table `topicos`.`alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topicos`.`alunos` ;

CREATE TABLE IF NOT EXISTS `topicos`.`alunos` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(60) NOT NULL,
  `nascimento` DATETIME NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topicos`.`materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topicos`.`materia` ;

CREATE TABLE IF NOT EXISTS `topicos`.`materia` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topicos`.`alunos_has_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topicos`.`alunos_has_materia` ;

CREATE TABLE IF NOT EXISTS `topicos`.`alunos_has_materia` (
  `alunos_matricula` INT NULL,
  `materia_cod` INT NULL
)ENGINE = InnoDB;

ALTER TABLE `alunos_has_materia` ADD CONSTRAINT `alunos_matricula` FOREIGN KEY ( `alunos_matricula` ) REFERENCES `alunos` ( `matricula` ) ;
ALTER TABLE `alunos_has_materia` ADD CONSTRAINT `materia_cod` FOREIGN KEY ( `materia_cod` ) REFERENCES `materia` ( `cod` ) ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
